### ISSUE TITLE
parser error with Version 0.3.10 during start

### ISSUE THREAD

**Issue by hebe2k** [snowdd1/homebridge-knx-de#41]
Hi @snowdd1,

ich bekomme bei jedem Start folgende Fehlermeldung im Log:

```
Loading custom types: Got an parser error:  SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-knx/lib/customtypes/knxthermostat.js:52:29)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Don't care, continue...
```

Homebridge läuft ansonsten ganz normal.

Gruß,
Henning

**Comment by hebe2k** [comment]
moved to homebridge-knx

**Comment by snowdd1** [comment]
Das ist derzeit leider normal, stört auch im Programmablauf nicht weiter. Es versucht eine Datei von GitHub zu laden und zu parsen (nicht-standard-Eigenschaften für Services) das klappt noch nicht. 
Da ich damit gerechnet habe dass das recht häufig scheitert habe ich das schon in einen try-catch-Block integriert so dass homebridge nicht abbricht wenn es passiert. 
Wird in einer der nächsten Versionen verschwinden.

**Comment by hebe2k** [comment]
Okay, danke für die Info.

**Comment by HolyGiraffe** [comment]
Meldung kommt noch 💃

**Comment by snowdd1** [comment]
Hi @HolyGiraffe, 
welche Version? in 0.3.10 war es noch drin, in 0.3.12 sollte es nicht mehr kommen!
Grüße!
