### ISSUE TITLE
Homebridge Startup Error after Update

### ISSUE THREAD

**Issue by KNXDUMMY** [snowdd1/homebridge-knx-de#44]
Hello,

I have updated Homebridge, Homebridge-KNX and KNXD. While KNXD is still working I cannot get Homebridge running. I have the fear that either a Path has changed since the last Version I used or I have trouble with user Rights. config.json and knx_config.json seem to work and I can see homebridge reading the file on startup but homebridge stops afterwards, here is the last bit of the log.

INFO registerSingleGA 1/1/12
[2017-04-13 13:37:07] [homebridge-knx.KNX] Done with [Aussenbereich] accessory
[2017-04-13 13:37:07] [homebridge-knx.KNX] We have read 11 devices from file.
[2017-04-13 13:37:07] [homebridge-knx.KNX] Saving config file!
---
[2017-04-13 13:37:07] Homebridge is running on port 51826.
Server Listening...localhost:18081/list
Loading custom types: Got an parser error:  SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-knx/lib/customtypes/knxthermostat.js:52:29)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Don't care, continue...
[2017-04-13 13:37:09] [homebridge-knx.KNX] Value changed, updating homebridge
[2017-04-13 13:37:09] [homebridge-knx.KNX] exiting writeValueHK()
buffer.js:94
    throw new TypeError('"value" argument must not be a number');
    ^

TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:94:11)
    at Parser.parseTelegram (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:84:43)
    at Parser.onData (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:150:12)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:36:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
pi@raspberrypi:~ $

I also made sure there is no second instance of homebridge is running.

Thanks for Help

Martin

**Comment by snowdd1** [comment]
Hi Martin,
this is the **German** issue list.  
However, as your issue has good cause, I will respond in English.  

The problem is a new feature I requested in `eibd` package, and pushed a faulty pull request. I hope that André, the maintainer of node-eibd, will accept my [new corrected pull request](https://github.com/andreek/node-eibd/pull/49) soon.

For the time being, you might install `eibd` version 0.3.7 which hadn't had the error.

**Comment by KNXDUMMY** [comment]
Hallo,

Vielen Dank das funktioniert :-)

LG

Martin
